# ref: https://docs.docker.com/compose/compose-file/
version: '3'

services:
  # Database
  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    ports:
        - '5432:5432'    
    environment:
      POSTGRES_PASSWORD: 'banana'
    networks:
      - pgsite
  
  # pgadmin4
  pg4:
    depends_on:
      - db
    image: dpage/pgadmin4
    restart: always
    ports:
      - '8080:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: 'postgres@domain.com'
      PGADMIN_DEFAULT_PASSWORD: 'banana'
    networks:
      - pgsite

networks:
  pgsite:

volumes:
  db_data: