# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: dolphin

  pg4:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: dolphin
    ports:
        - 80:80

  # adminer:
  #   image: adminer
  #   restart: no
  #   ports:
  #     - 8080:8080
