# MySQL + phpMyAdmin + Adminer

# docker run --rm --name dolphin -v mysql_datavolume:/var/lib/mysql -p 3306:3306 -p 33060:33060/tcp -d -e MYSQL_ROOT_PASSWORD=banana mysql
# docker run --rm --name myadmin -d -p 8080:80 --link dolphin:db phpmyadmin/phpmyadmin

# docker run --rm --name atlas -d -p 8888:8080 --link dolphin:db adminer
# docker run --rm --name atlas -d -p 8888:8080 --link dolphin:db -e ADMINER_DEFAULT_SERVER=dolphin adminer

version: '3'

services:
  # MySQL
  db:
    image: mysql:latest
    container_name: dolphin
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: banana
    networks:
      - dev_network

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: myadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: banana 
    networks:
      - dev_network

  adminer:
    # depends_on:
    #   - db
    image: adminer:latest
    container_name: atlas
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - 8888:8080
    networks:
      - dev_network

networks:
  dev_network:

volumes:
  db_data: