# Microsoft SQL Server + Adminer

# docker run --name maroon -e 'ACCEPT_EULA=Y' -e 'MSSQL_SA_PASSWORD=5HEe1Ybq' -p 1433:1433 -v sqlvolume:/var/opt/mssql -d mcr.microsoft.com/mssql/server:2019-latest

# docker run --rm --name atlas -d -p 8888:8080 --link dolphin:db adminer

version: "3"

services:
  # Microsoft SQL Server
  db:
    image: mcr.microsoft.com/mssql/server
    container_name: maroon
    volumes:
      - db_data:/var/opt/mssql
    restart: always
    ports:
      - '1433:1433'
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: 5HEe1Ybq
    networks:
      - dev_network
  # MySQL
  #   db:
  #     image: mysql:latest
  #     container_name: dolphin
  #     volumes:
  #       - db_data:/var/lib/mysql
  #     restart: always
  #     environment:
  #       MYSQL_ROOT_PASSWORD: banana
  #     networks:
  #       - dev_network

  # phpmyadmin
  #   phpmyadmin:
  #     depends_on:
  #       - db
  #     image: phpmyadmin/phpmyadmin
  #     container_name: myadmin
  #     restart: always
  #     ports:
  #       - '8080:80'
  #     environment:
  #       PMA_HOST: db
  #       MYSQL_ROOT_PASSWORD: banana
  #     networks:
  #       - dev_network

  adminer:
    depends_on:
      - db
    image: adminer:latest
    container_name: atlas
    ports:
      - 8888:8080
    networks:
      - dev_network

networks:
  dev_network:

volumes:
  db_data:
