version: '3'

networks:
  dev_network:

volumes:
  db1_data:
  db2_data:

services:
  # MySQL
  db1:
    image: mysql:latest
    container_name: dolphin
    volumes:
      - db1_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: banana
    ports:
      - '3306:3306'
    networks:
      - dev_network

  db2:
    image: mysql:latest
    container_name: whale
    volumes:
      - db2_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: coconut
    ports:
      - '3307:3306'
    networks:
      - dev_network

  # phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: myadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      # PMA_HOST: dolphin
      PMA_ARBITRARY: 1
    networks:
      - dev_network

  adminer:
    image: adminer:latest
    container_name: atlas
    environment:
      ADMINER_DEFAULT_SERVER: dolphin
    ports:
      - 8888:8080
    networks:
      - dev_network